import type { TablesInsert } from "@/../../database.types"

export type User = TablesInsert<"users">

export type Student = User       // role === "student"
export type FacultyMember = User // role === "faculty" | "admin" | etc.

// SectionData mirrors TablesInsert<"sections"> with:
//   - id, created_at, updated_at omitted (generated by Supabase)
//   - course_id optional (populated once the parent course is persisted)
export type SectionData =
  Omit<TablesInsert<"sections">, "id" | "created_at" | "updated_at" | "course_id"> & {
    course_id?: string
  }