export const CaseSection = {
  DEMOGRAPHICS: "DEMOGRAPHICS",
  HISTORY: "HISTORY",
  CLINICAL_DOCUMENTS: "CLINICAL_DOCUMENTS",
  ORDERS: "ORDERS",
  LABS: "LABS",
  DOCUMENTATION: "DOCUMENTATION",
  INTAKE_OUTPUT: "INTAKE_OUTPUT",
  MEDICATION_ORDERS: "MEDICATION_ORDERS",
  MEDICATION_ADMINISTRATIONS: "MEDICATION_ADMINISTRATIONS",
  MEDIA: "MEDIA"
} as const;

export type CaseSection = typeof CaseSection[keyof typeof CaseSection];
